services:
  db:
    build:
      context: .
      dockerfile: database/Dockerfile
    container_name: esus-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: esus
      POSTGRES_INITDB_ARGS: "--locale=pt_BR.UTF-8"
      LANG: pt_BR.UTF-8
      LC_ALL: pt_BR.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database:/dump
      - ./database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    command: >
      postgres
        -c shared_buffers=256MB
        -c work_mem=64MB
        -c maintenance_work_mem=512MB

volumes:
  pgdata:
